apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "kubernetes-deployment"
  namespace: "default"
  labels:
    app: "kubernetes-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kubernetes-deployment"
  template:
    metadata:
      labels:
        app: "kubernetes-deployment"
    spec:
      containers:
      - name: "container1"
        image: "us-central1-docker.pkg.dev/tribal-cortex-428712-n1/kubernetes/container1-image:latest"
        imagePullPolicy: Always  # Specify the image pull policy here
        volumeMounts:
          - mountPath: /home/nikulpokukadiya1998
            name: kubernetes-volume1
      volumes:
        - name: kubernetes-volume1
          persistentVolumeClaim:
            claimName: kubernetes-volume-claim1