# Cloud Build Trigger: $BUILD_ID
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "kubernetes-deployment"
  namespace: "default"
  labels:
    app: "kubernetes-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kubernetes-deployment"
  template:
    metadata:
      labels:
        app: "kubernetes-deployment"
    spec:
      containers:
      - name: "kubernetes-c1-sha256-1"
        image: "us-central1-docker.pkg.dev/csci5409kubernetes-417601/csci5409kubernetes/csci5409-k8s-c1"
        volumeMounts:
          - mountPath: /home/nikulpokukadiya1998
            name: kubernetes-volume1
      - name: "csci5409-k8s-c2-sha256-2"
        image: "us-central1-docker.pkg.dev/csci5409kubernetes-417601/csci5409kubernetes/csci5409-k8s-c2"
        volumeMounts:
          - mountPath: /home/nikulpokukadiya1998
            name: kubernetes-volume1
      volumes:
        - name: kubernetes-volume1
          persistentVolumeClaim:
            claimName: kubernetes-volume-claim1
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "kubernetes-deployment-hpa-y3nx"
  namespace: "default"
  labels:
    app: "kubernetes-deployment"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "kubernetes-deployment"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
