apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service
spec:
  selector:
    app: kubernetes-deployment
  ports:
    - name: microservice-port
      protocol: TCP
      port: 80
      targetPort: 6000
  type: LoadBalancer